version: '3.8'

services:
  pg-primary:
    image: postgres:17
    container_name: pg-primary
    restart: always
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customers
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - pg-primary-data:/var/lib/postgresql/data
      - ./primary/init:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"

  pg-replica:
    image: postgres:17
    container_name: pg-replica
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg-replica-data:/var/lib/postgresql/data
      - ./replica/init:/docker-entrypoint-initdb.d/
    depends_on:
      - pg-primary
    ports:
      - "5434:5432"

volumes:
  pg-primary-data:
  pg-replica-data:

